# ???????
server:
  port: 8080 # ????????
  servlet:
    context-path: /api/v1 # ??API?????, ?PRD????

# Spring Boot ????
spring:
  # ????????
  datasource:
    url: jdbc:mysql://localhost:3306/online_mall?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 10086111
    driver-class-name: com.mysql.cj.jdbc.Driver

# Jackson JSON ?? (????API?JSON??)
jackson:
  date-format: yyyy-MM-dd HH:mm:ss # ???????
  time-zone: Asia/Shanghai # ????

# MyBatis-Plus ????
mybatis-plus:
  # Mapper XML?????
  mapper-locations: classpath:/mapper/*.xml
# ????
global-config:
  db-config:
    # ????????: ??????????(e.g., user_name)?????Java?????(e.g., userName)
    map-underscore-to-camel-case: true
# ???
configuration:
  # ??MyBatis???????????????SQL??
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
