# ???????
server:
  port: 8080 # ????????
  servlet:
    context-path: /api/v1 # ??API?????, ?PRD????

# Spring Boot ????
spring:
  # ????????
  datasource:
    url: jdbc:mysql://localhost:3306/online_mall?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 10086111
    driver-class-name: com.mysql.cj.jdbc.Driver
  clickhouse:
    url: jdbc:ch:http://localhost:8123/online_mall # 你的 ClickHouse 地址
    username: default # 你的 ClickHouse 用户名
    password: 10086111

# Jackson JSON ?? (????API?JSON??)
jackson:
  date-format: yyyy-MM-dd HH:mm:ss # ???????
  time-zone: Asia/Shanghai # ????

mybatis-plus:
  # Mapper XML?????
  mapper-locations: classpath:/mapper/*.xml
  # ???? (global-config 和 configuration 需要移到 mybatis-plus 下面)
  global-config:
    db-config:
      # ????????: ??????????(e.g., user_name)?????Java?????(e.g., userName)
      map-underscore-to-camel-case: true
  # ???
  configuration:
    # ??MyBatis???????????????SQL??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 推荐服务配置
recommendation:
  service:
    url: http://127.0.0.1:5000/recommend # 推荐算法服务的地址
  trigger-training-endpoint:
    url: http://127.0.0.1:5000/trigger_training

app:
  recommendation:
    min-behaviors: 10

# JWT 配置
jwt:
  # 用于签名和验证的密钥，请务必修改为一个长且复杂的随机字符串
  secret: YourSuperLongAndSecureSecretKeyForJWTGenerationMustBeAtLeast256Bits
  # Token的过期时间 (毫秒)，这里设置为7天
  expiration: 604800000